name: sensor_iot
description: A hub for IoT Sensors

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  amplify_auth_cognito: ^1.6.2
  amplify_authenticator: ^1.5.3
  amplify_flutter: ^1.6.1
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  mqtt_client: ^10.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo_with_bgnd.png"

flutter_launcher_icons:
  android: true
  min_sdk_android: 21
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_with_padding_4@4x.png"
  image_path: "assets/logo_with_bgnd.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/foxy_sensor_logo.png"
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/certs/AmazonRootCA1.pem
    - assets/certs/certificate.pem.crt
    - assets/certs/private.pem.key
    - assets/logo_with_bgnd.png
    - assets/logo_with_padding_4@4x.png
    - assets/foxy_sensor_logo.png
    - assets/foxy_sensor_logo_title.png
    - assets/sunny_background.png
    - assets/smile.png
    - assets/smile_2.png
    - assets/frown.png
    - assets/drown.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
